import { readFileSync } from 'node:fs';

/** Reads the current AP-mode WiFi PSK, generated by firstboot.sh into /data/ap-psk. */
export function readApPsk(): string | null {
  try {
    return readFileSync('/data/ap-psk', 'utf8').trim() || null;
  } catch {
    return null;
  }
}
